In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Recommend.csv',names=['user_id', 'movie_id', 'rating', 'timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
5          298       474       4  884182806
6          115       265       2  881171488
7          253       465       5  891628467
8          305       451       3  886324817
9            6        86       3  883603013
10          62       257       2  879372434
11         286      1014       5  879781125
12         200       222       5  876042340
13         210        40       3  891035994
14         224        29       3  888104457
15         303       785       3  879485318
16         122       387       5  879270459
17         194       274       2  879539794
18         291      1042       4  874834944
19         234      1184       2  892079237
20         119       392       4  886176814
21         167       486       4  892738452
22         299       144       4  877881320
23         291       118       2  874833878
24         308         1       4  887736532
25          95       546       2  879196566
26          38        95       5  892430094
27         102       768       2  883748450
28          63       277       4  875747401
29         160       234       5  876861185
...        ...       ...     ...        ...
99970      449       120       1  879959573
99971      661       762       2  876037121
99972      721       874       3  877137447
99973      821       151       4  874792889
99974      764       596       3  876243046
99975      537       443       3  886031752
99976      618       628       2  891308019
99977      487       291       3  883445079
99978      113       975       5  875936424
99979      943       391       2  888640291
99980      864       685       4  888891900
99981      750       323       3  879445877
99982      279        64       1  875308510
99983      646       750       3  888528902
99984      654       370       2  887863914
99985      617       582       4  883789294
99986      913       690       3  880824288
99987      660       229       2  891406212
99988      421       498       4  892241344
99989      495      1091       4  888637503
99990      806       421       4  882388897
99991      676       538       4  892685437
99992      721       262       3  877137285
99993      913       209       2  881367150
99994      378        78       3  880056976
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [3]:
n_users = df.user_id.unique().shape[0] 
n_movies = df.movie_id.unique().shape[0]

In [4]:
n_users

943

In [5]:
 n_movies

1682

In [6]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0] 
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df, test_size=0.25)

In [8]:
len(train_data)

75000

In [9]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
train_data_matrix

array([[0., 3., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [10]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[5., 0., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
from sklearn.metrics import pairwise_distances


In [27]:
info=np.array([[1,2,3,4],[5,6,7,8]])

In [28]:
pairwise_distances(info)

array([[0., 8.],
       [8., 0.]])

In [30]:
info.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
pairwise_distances(info.T)

array([[0.        , 1.41421356, 2.82842712, 4.24264069],
       [1.41421356, 0.        , 1.41421356, 2.82842712],
       [2.82842712, 1.41421356, 0.        , 1.41421356],
       [4.24264069, 2.82842712, 1.41421356, 0.        ]])

In [16]:
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
user_similarity

array([[0.        , 0.84775601, 0.954478  , ..., 0.9185274 , 0.81874831,
        0.67458483],
       [0.84775601, 0.        , 0.91590237, ..., 0.96083938, 0.88698468,
        0.90777899],
       [0.954478  , 0.91590237, 0.        , ..., 0.90116676, 0.86527291,
        0.9612089 ],
       ...,
       [0.9185274 , 0.96083938, 0.90116676, ..., 0.        , 0.92838851,
        0.89936144],
       [0.81874831, 0.88698468, 0.86527291, ..., 0.92838851, 0.        ,
        0.87430005],
       [0.67458483, 0.90777899, 0.9612089 , ..., 0.89936144, 0.87430005,
        0.        ]])

In [17]:
user_similarity.shape

(943, 943)

In [18]:
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
movie_similarity

array([[0.        , 0.74821463, 0.75788783, ..., 1.        , 1.        ,
        1.        ],
       [0.74821463, 0.        , 0.81541932, ..., 1.        , 0.90789917,
        0.90789917],
       [0.75788783, 0.81541932, 0.        , ..., 1.        , 1.        ,
        0.88934333],
       ...,
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [1.        , 0.90789917, 1.        , ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.90789917, 0.88934333, ..., 1.        , 1.        ,
        0.        ]])

In [20]:
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
mean_user_rating

array([[0.43816885],
       [0.09334126],
       [0.06361474],
       [0.03804994],
       [0.22711058],
       [0.34958383],
       [0.72294887],
       [0.09750297],
       [0.04756243],
       [0.32580262],
       [0.29131986],
       [0.08561237],
       [0.90903686],
       [0.18133175],
       [0.12663496],
       [0.28418549],
       [0.04102259],
       [0.48097503],
       [0.03686088],
       [0.0588585 ],
       [0.22651605],
       [0.1979786 ],
       [0.2431629 ],
       [0.13495838],
       [0.13198573],
       [0.14090369],
       [0.03804994],
       [0.13258026],
       [0.05410226],
       [0.08026159],
       [0.0648038 ],
       [0.05588585],
       [0.03686088],
       [0.03151011],
       [0.03983353],
       [0.02437574],
       [0.10879905],
       [0.19619501],
       [0.03269917],
       [0.04221165],
       [0.08561237],
       [0.30856124],
       [0.39060642],
       [0.23543401],
       [0.07609988],
       [0.03864447],
       [0.04280618],
       [0.100

In [21]:
ratings_diff = (train_data_matrix - mean_user_rating) 


In [23]:
ratings_diff.shape

(943, 1682)

In [31]:

user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.57002982,  0.5497796 ,  0.48684029, ...,  0.28970649,
         0.28975325,  0.28949326],
       [ 1.3016549 ,  0.25596453,  0.14382359, ..., -0.07438242,
        -0.07288971, -0.07275091],
       [ 1.2935442 ,  0.22038905,  0.11706987, ..., -0.10389697,
        -0.1021653 , -0.10210258],
       ...,
       [ 1.14900886,  0.1804446 ,  0.07592708, ..., -0.1307813 ,
        -0.12986003, -0.12977553],
       [ 1.33799607,  0.28982139,  0.20482081, ..., -0.01456488,
        -0.01361386, -0.01349362],
       [ 1.36933097,  0.34003308,  0.27717045, ...,  0.08158773,
         0.0814588 ,  0.08144978]])

In [32]:
movie_pred = train_data_matrix.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

array([[0.36651732, 0.37868509, 0.40325315, ..., 0.44047019, 0.4325242 ,
        0.42729005],
       [0.08014273, 0.09221823, 0.08790721, ..., 0.0913712 , 0.09310205,
        0.09358518],
       [0.06156971, 0.06451674, 0.06162444, ..., 0.06038199, 0.06341184,
        0.06406742],
       ...,
       [0.02197715, 0.02922815, 0.02802878, ..., 0.03340009, 0.03299739,
        0.0331134 ],
       [0.12288488, 0.13317307, 0.13907678, ..., 0.14405763, 0.14393572,
        0.14439454],
       [0.18758399, 0.18575924, 0.20396719, ..., 0.23427824, 0.22556135,
        0.22523258]])

In [33]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(pred, test):
    pred = pred[test.nonzero()].flatten() 
    test = test[test.nonzero()].flatten()
    return sqrt(mean_squared_error(pred, test))

In [20]:
rmse(user_pred, test_data_matrix)

3.138384405490276

In [21]:
rmse(movie_pred, test_data_matrix)

3.4647957787706685